---
- name: import config
  hosts: my-firewall
  connection: local
  gather_facts: False

  vars:
    cfg_file: candidate-template-empty.xml

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: wait for SSH (timeout 10min)
    wait_for: port=22 host='{{ provider.ip_address }}' search_regex=SSH timeout=600

  - name: checking if device ready
    panos_check:
      provider: '{{ provider }}'
    register: result
    until: not result|failed
    retries: 10
    delay: 10

  - name: import configuration
    panos_import:
      ip_address: '{{ provider.ip_address }}'
      username: '{{ provider.username }}'
      password: '{{ provider.password }}'
      file: '{{cfg_file}}'
      category: 'configuration'
    register: result

  - name: load configuration
    panos_loadcfg:
      ip_address: '{{ provider.ip_address }}'
      username: '{{ provider.username }}'
      password: '{{ provider.password }}'
      file: '{{result.filename}}'
      commit: False

  - name: set admin password
    panos_administrator:
      provider: '{{ provider }}'
      admin_username: 'admin'
      admin_password: '{{ provider.password }}'
      superuser: True
      commit: False

  - name: commit (blocks until finished)
    panos_commit:
      provider: '{{ provider }}'